# Generated by Django 5.2.13 on 2026-05-03 13:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='Корпус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('teacher', 'Преподаватель'), ('admin', 'Администратор')], default='teacher', max_length=20, verbose_name='Роль')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('offboarding', 'Увольняется'), ('dismissed', 'Уволен')], default='active', max_length=20, verbose_name='Статус сотрудника')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Кафедра / подразделение')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Инвентарный номер')),
                ('category', models.CharField(choices=[('computer', 'Компьютер / ПК'), ('laptop', 'Ноутбук'), ('monitor', 'Монитор'), ('printer', 'Принтер / МФУ'), ('projector', 'Проектор'), ('furniture', 'Мебель'), ('other', 'Прочее')], default='other', max_length=30, verbose_name='Категория')),
                ('condition', models.CharField(choices=[('good', 'Исправно'), ('needs_repair', 'Требует ремонта'), ('broken', 'Неисправно'), ('written_off', 'Списано')], default='good', max_length=20, verbose_name='Состояние')),
                ('description', models.TextField(blank=True, verbose_name='Описание / Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно (не списано)')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата приобретения')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Балансовая стоимость (₽)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней проверки')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_set', to=settings.AUTH_USER_MODEL, verbose_name='Закреплено за')),
                ('last_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_equipment', to=settings.AUTH_USER_MODEL, verbose_name='Кто последний проверял')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_set', to='inventory.location', verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Оборудование (ТМЦ)',
                'verbose_name_plural': 'Оборудование (ТМЦ)',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('verified', 'Подтверждено наличие'), ('transferred', 'Передано сотруднику'), ('moved', 'Перемещено в другую аудиторию'), ('reported_lost', 'Сообщено об утере'), ('assigned', 'Закреплено (администратором)'), ('unassigned', 'Откреплено (администратором)'), ('written_off', 'Списано')], max_length=30, verbose_name='Тип события')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.equipment', verbose_name='Оборудование')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='inventory.location', verbose_name='Откуда')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to=settings.AUTH_USER_MODEL, verbose_name='От кого')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='inventory.location', verbose_name='Куда')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Запись истории',
                'verbose_name_plural': 'История перемещений',
                'ordering': ['-timestamp'],
            },
        ),
    ]
